version: '3.9'
services:
  redis:
    image: redis/redis-stack:7.2.0-v13
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - 6379:6379
      - 13333:8001
    mem_limit: '200m'
    command: >
      ./entrypoint.sh
      --maxmemory 200000000
