version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env.compose.local
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    env_file:
      - .env.compose.local
    volumes:
      - mongo-express-data:/var/lib/mongo-express

volumes:
  mongo-data:
  mongo-express-data:
