version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    command: mongod --replSet rs0 --bind_ip_all

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    env_file:
      - .env.compose.local
    volumes:
      - mongo-express-data:/var/lib/mongo-express

  mongo-replica-setup:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./initiate_mongo:/initiate_mongo
    restart: 'no'
    entrypoint: ['bash', '/initiate_mongo/initiate_replica.sh']

volumes:
  mongo-data:
  mongo-express-data:
